<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeFuels.aspx.cs" Inherits="WebFormExample.CodeFuels" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindFuel" runat="server" Text="Label">Топливо</asp:Label><asp:TextBox ID="TextBoxFindFuel" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindFuel" runat="server" Text="Найти" OnClick="ButtonFindFuel_Click" />
    <br />        
        <asp:GridView ID="GridViewFuel" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewFuel_RowCancelingEdit" 
            OnRowDeleting="GridViewFuel_RowDeleting" 
            OnRowEditing="GridViewFuel_RowEditing" 
            OnRowUpdating="GridViewFuel_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewFuel_PageIndexChanging" 
            Caption="Виды топлива" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="FuelId" HeaderText="Код" SortExpression="FuelId" />
                <asp:BoundField DataField="FuelType" HeaderText="Название" SortExpression="FuelType" />
                <asp:BoundField DataField="FuelDensity" HeaderText="Плотность" SortExpression="FuelDensity" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новый вид топлива:</strong>
            <br />
            <asp:label runat="server">Вид топлива:</asp:label><asp:TextBox ID="TextBoxFuelType" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Плотность топлива:</asp:label><asp:TextBox ID="TextBoxFuelDensity" runat="server"></asp:TextBox>
            <br />
            <asp:RangeValidator runat="server" ID="ValidateFuelDensity" ControlToValidate="TextBoxFuelDensity" 
                MinimumValue=0 MaximumValue="3" Type="Double" ErrorMessage="Значение плотности не входит в указанный диапазон" Display="dynamic" 
                SetFocusOnError="True">*
            </asp:RangeValidator>
            <asp:ValidationSummary runat="server" ID="Summary" DisplayMode="BulletList"  HeaderText="<b>Пожалуйста, исправьте следующие ошибки: </b>" ShowSummary="true" />
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddFuel" runat="server" Text="Добавить" OnClick="ButtonAddFuel_Click" />

        </td>
</tr>
</table>
    </asp:Content>
