<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CodeFuels.aspx.cs" Inherits="WebFormExample.CodeFuels" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
        <strong>Виды топлива</strong>
        <asp:GridView ID="GridViewFuel" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AllowSorting="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            EnableSortingAndPagingCallbacks="True" 
            OnRowCancelingEdit="GridViewFuel_RowCancelingEdit" 
            OnRowDeleted="GridViewFuel_RowDeleted" 
            OnRowDeleting="GridViewFuel_RowDeleting" 
            OnRowEditing="GridViewFuel_RowEditing" 
            OnRowUpdated="GridViewFuel_RowUpdated" 
            OnRowUpdating="GridViewFuel_RowUpdating" >
            <Columns>
                <asp:BoundField DataField="FuelId" HeaderText="Код" SortExpression="FuelId" />
                <asp:BoundField DataField="FuelType" HeaderText="Название" SortExpression="FuelType" />
                <asp:BoundField DataField="FuelDensity" HeaderText="Плотность" SortExpression="FuelDensity" />
            </Columns>

    </asp:GridView>

    </asp:Content>
